repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
        types: [go]

      - id: go-test
        name: go test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        types: [go]

      - id: kumite-static-analysis
        name: kumite static analysis
        entry: make static-analysis
        language: system
        pass_filenames: false
        always_run: true

      - id: kumite-build
        name: kumite build
        entry: make build
        language: system
        pass_filenames: false
        always_run: true
